[package]
name = "dbgify"
version = "0.1.0"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-dbg = { path="./derive-dbg", version="0.1" }
crossterm = "0.9"
